### ISSUE TITLE
Audio-only users can't be heard

### ISSUE THREAD

**Issue by bekriebel** [luvolondon/fvtt-module-jitsiwebrtc#12]
My fix in PR #10 isn't complete. For some reason, an audio-only user still isn't heard despite them being joined to the meeting. I'll be trying to debug this over the next couple of days if you'd like.

The easiest way to test (if you don't have a system without a camera) is to either set the camera to `Never Send Camera` or have the browser block permission on the camera device.

**Comment by luvolondon** [comment]
Ok, good to know. I´ll also do testing.

**Comment by luvolondon** [comment]
Thank you for your work on this. I´m on vacation this week, will get back to this next week. If you have problems with audio only, do you configure FVTT with "Audio only" or "Audio & Video" in the general settings?

**Comment by bekriebel** [comment]
It happens in both cases. In Audio Only, no one hears anyone. In Audio & Video - anyone joining without a camera can't be heard. The primary issue turned out to be this:

```
        assignStreamToVideo(stream, video) {
		this.debug("assignStreamToVideo stream:", stream, " video:", video);
		if ( stream && (stream.getVideoTracks().length > 0) ) {
```

Since `assignStreamToVideo` assigns the stream to the `<video>` element, it needs to happen for both video and audio tracks and shouldn't filter on if the stream has a video track or not.

**Comment by sharpchris** [comment]
Confirmed this is the case for our group as well.

**Comment by luvolondon** [comment]
I´ve added your fixes to the source, thank you again for the findings. I tried to limit the call to video.srcObject = stream to only ones if we have audio & video, but did not succeed. So we just do it as you proposed and call it for twice in case audio and video tracks arrive from remote one after the other. 

Regarding your other fix for onUserAudioStreamChange:
I see the need for reversing the userSettings.canBroadcastAudio check and changed that in the code. But why do you think the extra call to this.setVideoStream(userId, stream); is needed? With every refresh of a client there is so much updating going on I try to limit these calls to a minimum.

**Comment by bekriebel** [comment]
@luvolondon Oh, you're absolutely right. In fact, I had another commit that I must have missed adding into that branch that removes that and also removes it from https://github.com/luvolondon/fvtt-module-jitsiwebrtc/blob/236fa54d26ca2d53f5358627d3195a791b2d3cb6/jitsirtc.js#L733. I tested it out and that line can also be safely removed. As you said, it already does far too many updates as is :-)
