### ISSUE TITLE
Check new Edge

### ISSUE THREAD

**Issue by luvolondon** [luvolondon/fvtt-module-jitsiwebrtc#2]

**Comment by crobibero** [comment]
Tested and working in Edge Version 80.0.361.111 (Chromium based)

**Comment by luvolondon** [comment]
Same here with 3 PCs: FF, Chrome and Edge Chromium client, video + sound working
Update: There are problems with FF when user re-joines connection etc. , atm Jitsi ist not fully ok with FF, see https://community.jitsi.org/t/browser-support-warning-when-using-the-latest-firefox-71-0-version-on-meet-jit-si/21180/8
