### ISSUE TITLE
Calling "game.settings.set('jitsiwebrtc')" can result in errors displayed for users without permission

### ISSUE THREAD

**Issue by CrashZebra** [luvolondon/fvtt-module-jitsiwebrtc#20]
The code calls game.settings.set('jitsiwebrtc'...) if the module settings are blank to populate the default values. That call can result in an error message on the screen if a user doesn't have permission to edit those values.

**Comment by bekriebel** [comment]
I believe this issue is resolved in the latest version. If it isn't, please comment and I can re-open it.
