### ISSUE TITLE
ERR_NAME_NOT_RESOLVED - odd formatting of address?

### ISSUE THREAD

**Issue by Svarto** [luvolondon/fvtt-module-jitsiwebrtc#21]
Hi,

I am trying to connect to a self-hosted Jitsi server on the home LAN. I am not getting it to work, and something is odd with the plugin as I am not even registering a connection attempt on the Jitsi server. It looks like it adds an additional https to the address, which of course does not resolve - not sure what I am doing wrong here?

My setup inside FoundryVTT
![Screenshot from 2020-07-24 12-06-33](https://user-images.githubusercontent.com/24279217/88381180-71b91e80-cd95-11ea-9554-d60d0280cc35.png)

The error in the Chromium browser console (not the extra https in the address)
![Screenshot from 2020-07-24 12-06-42](https://user-images.githubusercontent.com/24279217/88381199-7b428680-cd95-11ea-9063-8922fd602dc4.png)

But the original console setup makes it look like the address used is correct (i.e. without the extra https)?
![Screenshot from 2020-07-24 12-06-55](https://user-images.githubusercontent.com/24279217/88381221-8695b200-cd95-11ea-94c2-36450dadac6b.png)

I can connect from the FoundryVTT server to the https://jitsi.svarto-server.com/http-bind fine and get the "BOSH is ready" message from Jitsi. I am using docker-meet-jitsi setup, and it is working fine for other conference (video & audio) use.

**Comment by bekriebel** [comment]
Can you check your settings under the Module Settings page and see if something is set incorrectly there? It's possible this was formatted wrong when the server information was entered:

![image](https://user-images.githubusercontent.com/183779/88696324-f8cd0600-d0b7-11ea-8ea3-05294c587bf3.png)

**Comment by bekriebel** [comment]
I believe this issue is resolved. If it isn't, please comment and I can re-open it.
