### ISSUE TITLE
Player's Mic is not being recognized

### ISSUE THREAD

**Issue by OlsenAviles** [luvolondon/fvtt-module-jitsiwebrtc#22]
We've exhausted every setting we could think of and we were never able to get one of my players mic to work. Foundry A/V works pretty well for him when we use P2P but once we I activate the Jitsi Module his mic is no longer recognized. The webpage is allowed to use the mic but it seems like it doesn't "ask" for permission. He doesn't have this issue with any other a/v client. We even used Jitsi Meet we no issues. We spent two hours trying to figure it out but got nowhere. The console did show a few strange errors that were Jitsi related.

Things we've tried.
Permission within the browser
Hard reset
clearing cookies
permissions within Windows
Settings within Foundry
different browser

`game:1 A cookie associated with a cross-site resource at http://meet.jit.si/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
game:1 A cookie associated with a cross-site resource at http://jit.si/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
forgevtt-module.js?ver=1.9:676 
                                                                #               
                                                              (%                
                              %%%%%                          %%/                
                             %%%%%%%%,                     %%%%         *       
                             .%%%%%%%%%%                  %%%%.     %%%         
                              #%%%%%%%%%%%              %%%%%% %%%%%%,          
                             (%%%%%%%%%%%%%        %* ,%%%%%%%%%%%%%            
                        %%%%%%%%%%%%%%%%%%%%      %%%%%%%%%%%%%%%%              
                  #%%%%%%%%%%%    %%%%%%%%%%,    %%%%%%%%%%%%%%%%%%%%%%%        
             %%%%%%%%%%%.          %%%%%%%%%%   %%%%%%%  %%%%%%%%%              
       %%%%%%%%%%%#                  %%%%      (%*       %%#                    
   (%%%%%%%%%                                                                   
    ,%%#                       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%            
                 *%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%            
                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%,        
                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/    
                       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/    
                           #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
                               %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%            
                               %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%            
                                        %%%%%%%%%%%%%%%%%%                      
                                       %%%%%%%%%%%%%%%%%%%%/                    
                                     %%%%%%%%%%%%%%%%%%%%%%%%                   
                                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%                 
                                ,%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%              
                           #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
                                                                                 
                                     Welcome to The Forge.

Logger.js:154 2020-07-30T07:51:09.205Z [modules/browser/BrowserCapabilities.js] <new a>:  This appears to be chrome, ver: 84.0.4147.105
LocalStatsCollector.js:22 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ LocalStatsCollector.js:22
n @ bootstrap:19
(anonymous) @ statistics.js:1
(anonymous) @ lib-jitsi-meet.min.js:1
n @ bootstrap:19
(anonymous) @ BridgeChannel.js:1
(anonymous) @ lib-jitsi-meet.min.js:10
n @ bootstrap:19
(anonymous) @ lib-jitsi-meet.min.js:1
(anonymous) @ lib-jitsi-meet.min.js:1
n @ bootstrap:19
(anonymous) @ ActiveDeviceDetector.js:1
(anonymous) @ lib-jitsi-meet.min.js:10
n @ bootstrap:19
(anonymous) @ JitsiMeetJS.js:1
(anonymous) @ lib-jitsi-meet.min.js:17
n @ bootstrap:19
(anonymous) @ index.js:3
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ lib-jitsi-meet.min.js:1
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:1
gridScale.js:10 Grid Scale | Drawing Layer | Loaded into Drawing Layer
gridScale.js:1186 Grid Scale | ** Finished Loading **
foundry.js:5516 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  '

**Comment by OlsenAviles** [comment]
We did figure out a workaround, If we use WebRTC Tweaks he can connect to jitsi via the Main Jitsi meet page and that seems to work. But for whatever reason it refuse to recognize his mic when trying it through Foundry.

**Comment by bekriebel** [comment]
@OlsenAviles A new version of the module was just released. Can you test this version out and see if it resolves the issue?

**Comment by cyface** [comment]
@bekriebel I am also seeing that it appears to be a permissions issue of some kind. If I make multiple Gamemaster accounts (with different names), they can all connect 100% of the time.  But folks with only the "Player" permission never get prompted for camera/mic access.  Even if pre-authorizing the browser's permissions, it never even tries to grab the A/V stuff from the browser.   This is with Foundry 0.6.6, and Jitsi WebRTC Client 0.3.3.  Thank you!

Edit: I found the permissions panel required turning on the ability for "Players" to broadcast A/V and this fixed it for me.  Cheers!

**Comment by bekriebel** [comment]
I'm going to go ahead and close this issue. If anything issues still persist, please let me know!
