### ISSUE TITLE
Jitsi Docker defaults to non domain name XMPP rooms

### ISSUE THREAD

**Issue by SimmyD** [luvolondon/fvtt-module-jitsiwebrtc#26]
Thanks for your work on this project.  It amazing seeing jitsi used for this purpose.

When creating Jitsi from the Docker guide it keeps the defaults for:

XMPP Domain = meet.jitsi
MUC Domain = muc.meet.jitsi

If you put "meet.jitsi" as the signalling server url then put "<actualdominname>/http-bind" in the bosh settings along with muc.meet.jitsi as the muc override everything works as expected.

It may just not be clear you can put the xmpp domain in the signalling server url to override it.

Hope this make sense.

**Comment by SimmyD** [comment]
fixed by #27

**Comment by bekriebel** [comment]
I'm not quite sure how that is working unless this is using a privately routed domain. `meet.jitsi` isn't a valid domain, so setting that to the signaling server URL shouldn't work outside of your local network.

**Comment by SimmyD** [comment]
Hey @bekriebel have commented in the pull request :)

**Comment by bekriebel** [comment]
This shouldn't be needed any more since we now read the config from the designated server. Regardless, if it is needed, the new release also adds this setting as requested.
