### ISSUE TITLE
Webcam for user appears frozen but looks correct for others

### ISSUE THREAD

**Issue by Klindel** [luvolondon/fvtt-module-jitsiwebrtc#29]
I'm trying to figure out the root cause, but in my group when using this with 5 people.  Often, everyone will say their video of themselves appears frozen but everyone else appears fine.  In reality it's only frozen on their screen, everyone else is seeing them just fine.

This is the only error I see at the moment:

Logger.js:154 2020-09-12T22:22:55.915Z [modules/RTC/BridgeChannel.js] <RTCDataChannel.e.onmessage>:  Failed to parse channel message as JSON:  {"lastNEndpoints":[83a01eb4, 3bbcc0d0, 2a612dc1, 0fc12781, bdac03c9],"conferenceEndpoints":[83a01eb4, 3bbcc0d0, 2a612dc1, 0fc12781, bdac03c9],"endpointsEnteringLastN":[2a612dc1],"colibriClass":"LastNEndpointsChangeEvent"} SyntaxError: Unexpected token a in JSON at position 21
    at JSON.parse (<anonymous>)
    at RTCDataChannel.e.onmessage (BridgeChannel.js:295)

Based on the output, it looks like the error is because the values within the lists aren't properly quoted as strings.  I just discovered the debug output flag and will turn it on the next time it occurs, which will be next week

**Comment by bekriebel** [comment]
I just recently found a solution for this and it will be in the next release.

**Comment by Bapf** [comment]
Having the same issue quite a lot.
