### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [luvolondon/fvtt-module-jitsiwebrtc#30]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by bekriebel** [comment]
Thanks for this request. Yes, I will add this functionality in an upcoming release.

**Comment by bekriebel** [comment]
Implemented in v0.4.6

**Comment by lozalojo** [comment]
Thanks, I've just pushed a PR to translate the module to spanish
