### ISSUE TITLE
Bridge Channel send: no opened channel

### ISSUE THREAD

**Issue by supervj** [luvolondon/fvtt-module-jitsiwebrtc#36]
Here is the error I get in the console log:

2020-10-30T01:57:12.017Z [modules/RTC/BridgeChannel.js] <l._send>:  Bridge Channel send: no opened channel.

o	@	Logger.js:154
_send	@	BridgeChannel.js:379
sendMessage	@	BridgeChannel.js:190
sendChannelMessage	@	RTC.js:932
ie.sendEndpointMessage	@	JitsiConference.js:2515
ie.sendMessage	@	JitsiConference.js:2559
(anonymous)	@	JitsiConference.js:349
sendRequest	@	e2eping.js:93

**Comment by supervj** [comment]
Using version 0.4.1 on a local host of Foundry trying to use the default settings of the module.  This has happened to me on both foundry 0.6.6 and 0.7.5

**Comment by luvolondon** [comment]
I had this error when I used "username" and not "username@_hostname of jitsi server_" as the authorization info for the jitsi server.

**Comment by supervj** [comment]
So do I have to create a custom server to be able to see that setting or did I miss an option somewhere?

**Comment by luvolondon** [comment]
I thought you got the error when using your own server. If it happens with the public Jitsi server, I guess this indicates the service doesn´t work with this module atm. I´m also trying to connect to the public Jitsi server for the last days without any luck. It´s unclear what´s the reason for this.

**Comment by bekriebel** [comment]
Strange... On one of my test servers, it seems to be working fine with the default `FVTT` (beta jitsi meet) service. On another one it is not. I'll see if I can find a difference between the two.

**Comment by bekriebel** [comment]
Okay, I see the problem with the BridgeChannel. It looks like the beta jitsi meet server no longer supports BOSH for the datachannel and must use websocket. We'll either need to make it so we can optionally switch between BOSH/websocket, or make it so we can auto-detect which one to use.

@luvolondon, the more I think about it, the more I like the idea of using the `config.js` values from the server. That *should* give us a good starting config that we can then tweak with specific values.

**Comment by supervj** [comment]
Thanks I will try this out tonight

**Comment by supervj** [comment]
It worked well with 7 people connected. Occasionally our video froze a little, but for the most part it worked very well, thanks again!
