### ISSUE TITLE
Stuck on mute when using voice activation

### ISSUE THREAD

**Issue by Bapf** [luvolondon/fvtt-module-jitsiwebrtc#38]
I've just tested this behaviour with version 0.4.0 and 0.4.1 on Chrome and Firefox:

When using "always on" or "push to talk" for audio everything works fine.

But when using "voice activation" the client gets stuck on mute if it ever enters this state. (Which one could see when joining with an external jitsi meet client where the mute icon is shown.)
Means audio is working right after joining a session or after muting and unmuting it by hand for as long as I talk (or there is sound). But as soon as I stop talking an the clients gets muted it never gets unmuted again. At least not automatically. Muting and unmuting by hand works (till it gets automuted again).

**Comment by bekriebel** [comment]
This should now be fixed with v0.4.3.
