### ISSUE TITLE
Leaving players are not removed from the avatar list

### ISSUE THREAD

**Issue by luvolondon** [luvolondon/fvtt-module-jitsiwebrtc#4]

**Comment by luvolondon** [comment]
It looks like this also happens with Firefox client leaving. It does not happen with Chrome / Chromium based browsers.

**Comment by dinandmentink** [comment]
Can confirm this. Firefox users are consistently not disconnected when closing window.

**Comment by vindr20** [comment]
I also see this behavior on chrome, actually. If a player closes their window, I see their video go out, but the avatar box is still there.

**Comment by bekriebel** [comment]
I believe this issue is resolved in the latest version. If it isn't, please comment and I can re-open it.
