### ISSUE TITLE
0.4.4 connectivity issues

### ISSUE THREAD

**Issue by feltz916** [luvolondon/fvtt-module-jitsiwebrtc#44]
Hey guys, i had another session tonight and connectivity was very bad, worse than the previous build (0.4.2. We spent a good hour trying to get everyone connected, and no matter what, we couldnt get it working 100% and ended up using a split configuration (everyone used a direct connection to my jitisi server in a different browser window for audio)

The issues we had:

1. Audio seemed as if it was using peer to peer connection, rather than server -> client. There were many instances where one person could not hear one or two other people. But the people they could not hear, were heard by others.
2. Many people could not see video of others until multiple refreshes.

After an hour of attempting to get this working, i just have my players the direct URL to my jitsi server, and every player (8 of us total) connected, audio and video both worked flawlessly. Really not sure what other data debugging i can do for data points.

**Comment by bekriebel** [comment]
Could you try using the default Jitsi server (by selecting `FVTT` instead of `Custom`)? There are some versions of Jitsi and lib-jitsi-meet that I've seen terrible results from. I'm curious if using the public Jitsi server will prove to be any better.

**Comment by feltz916** [comment]
Sorry, forgot to add that was one of my steps before throwing in the towel. It was nearly identical results using the public jitsi.

**Comment by bekriebel** [comment]
I added some changes to v0.4.5 that I'm hoping will clear up the issues. When you get a chance, can you test this version out and report back please, @feltz916?
