### ISSUE TITLE
Bug: Custom Jitsi URLs overriden by config.js values

### ISSUE THREAD

**Issue by laurigates** [luvolondon/fvtt-module-jitsiwebrtc#46]
I'm running Foundry and Jitsi in separate Docker environments. For Jitsi I'm using https://github.com/jitsi/docker-jitsi-meet.
They're both behind different FQDNs in the form jitsi.example.com and foundry.example.com.

FoundryVTT version 0.7.6
JitsiWebRTC version 0.4.5

- I configured the A/V server in Foundry to use jitsi.example.com, which didn't work
- I noticed failed queries to https://foundry.example.com/http-bind?room=xxxxxxxxxxxxxxxxxxxx
- I configured custom URLs for the Jitsi domain and bosh
- Queries were still made to https://foundry.example.com/http-bind?room=xxxxxxxxxxxxxxxxxxxx
- I noticed JitsiWebRTC fetches https://jitsi.example.com/config.js, which has the bosh URL configured as `/http-bind`

The bosh url is appended to the path to the FQDN of the foundry container instead of the specified Jitsi server.
I got my setup working by changing the bosh URL in config.js on the Jitsi container to an absolute URL, `//jitsi.example.com/http-bind`.

So it seems there's some issue with how the URLs in config.js are handled and how the custom URLs are applied.

**Comment by bekriebel** [comment]
Thanks. I found the error and will have it fixed in the next version.

**Comment by bekriebel** [comment]
Fixed in v0.4.6
