### ISSUE TITLE
Users connected to the room via the full Jitsi client ignore Audio/Video Conferencing Mode setting

### ISSUE THREAD

**Issue by eclarke12** [luvolondon/fvtt-module-jitsiwebrtc#48]
fvtt: 077
jitsirtc: 046

When a user connects to the Jitsi room via the standalone URL, their audio/video settings do not respect the Audio/Video Conferencing Mode setting in the AV Config:
![image](https://user-images.githubusercontent.com/42503461/99839465-95139080-2b1f-11eb-940c-e407aa04f9c8.png)

Even though it shows audio muted on the video frame for the user, they can still broadcast audio in this case.

**Comment by bekriebel** [comment]
Since they are connecting with the external URL, FVTT has no control over their connection. The best option is for the user just to mute themselves as these settings can't be passed through.

**Comment by eclarke12** [comment]
The workaround you proposed is what we are doing, but I assumed since you were capturing and displaying the stream you could possibly adjust what is included. Another idea I had is that since the AV Preferences are known I believe you can define the functionality of a Jitsi room on create (eg. mute audio/video)? Just a thought

**Comment by bekriebel** [comment]
I'll re-open and take a look at some point to see if this is feasible.

**Comment by bekriebel** [comment]
I tested this out. Unfortunately, Jitsi seems to ignore the request to mute the entire channel when creating the room with `startMuted` and `startSilent`. Unless Jitsi provides this functionality with their API, there's not much I can do except control what happens on the FVTT side.

The newest release has some more improvements around this, but I'm afraid there's nothing more I can do for those using the full jitsi meet client.
