### ISSUE TITLE
Console error whenever module enabled

### ISSUE THREAD

**Issue by benbarbour** [luvolondon/fvtt-module-jitsiwebrtc#49]
I'm seeing this error whenever the I load a world with this module enabled.

```
2020-12-01T07:17:11.121Z [modules/xmpp/xmpp.js] <tryParseJSONAndVerify>:  SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    tryParseJSONAndVerify xmpp.js:723
    _onPrivateMessage xmpp.js:768
    run strophe.umd.js:1875
    _dataRecv strophe.umd.js:3157
    forEachChild strophe.umd.js:830
    _dataRecv strophe.umd.js:3146
    _onRequestStateChange strophe.umd.js:5012
Logger.js:154:22
    o Logger.js:154
    tryParseJSONAndVerify xmpp.js:743
    _onPrivateMessage xmpp.js:768
    run strophe.umd.js:1875
    _dataRecv strophe.umd.js:3157
    forEachChild strophe.umd.js:830
    _dataRecv strophe.umd.js:3146
    _onRequestStateChange strophe.umd.js:5012
```

The actual communication seems to be pretty good, so this doesn't seem to have much of an impact. I have 6 players, and all seven of us can talk alright, except for one drops for a few seconds once every 30 seconds or so. Pretty sure that it's her terrible WiFi though.

**Comment by bekriebel** [comment]
Hrmm... That error is coming from within the Jitsi javascript library. Are there any additional messages/errors around that error? If you turn on debugging from the module settings, that may provide some more detail.

**Comment by benbarbour** [comment]
Well, I can't seem to reproduce it now. I was seeing it quite consistently for a few days though. Wouldn't even need anyone else logged in. Weird.

**Comment by bekriebel** [comment]
Hrmm... If you were connected to the default beta jitsi meet server, it's possible that it was something on their end. I've definetly seen that server occasionally have issues. I'll go ahead and close this ticket - feel free to re-open if it keeps happening.
