### ISSUE TITLE
Atm Jitsi Meet is only 100% ok for Chrome/Chromium. 

### ISSUE THREAD

**Issue by luvolondon** [luvolondon/fvtt-module-jitsiwebrtc#5]
see https://community.jitsi.org/t/browser-support-warning-when-using-the-latest-firefox-71-0-version-on-meet-jit-si/21180/8 for updates

**Comment by luvolondon** [comment]
https://github.com/jitsi/jitsi-meet/issues/4758

**Comment by mohicanb** [comment]
Hello, are the other Blink-based browsers like Brave https://brave.com/ and Falkon https://www.falkon.org/ 100% compatible with Jitsi Meet ?
If so please add them to the recommanded browsers list.

**Comment by bekriebel** [comment]
I believe this issue is resolved in the latest version. If it isn't, please comment and I can re-open it.
