### ISSUE TITLE
Some video streams not working when multiple users connect

### ISSUE THREAD

**Issue by feltz916** [luvolondon/fvtt-module-jitsiwebrtc#52]
Really dont know what else to do to help debug this, but this was my first attempt to try to get it working again since the last update.

For many users, we see "some" video streams. We see our own video, but the video is not transmitted to the jitsi server, or something else is broken as its not showing up for anyone else.

Attaching screen shots of an example of what it looks like in Foundry, as well as on the Jitsi server when connecting direct.

Steps to try to troubleshoot:
* Refreshing individual browsers
* Disabling and re-enabling video

Was not able to work around this issue, ended up just connecting to my Jitsi server directly, and everyones stream was working perfectly.
![JitsiBug](https://user-images.githubusercontent.com/7417818/103025873-8990fc00-4507-11eb-9b96-07c0910db19a.JPG)
![JitsiBug2](https://user-images.githubusercontent.com/7417818/103025881-8d248300-4507-11eb-87bb-85e46be6f88e.JPG)

**Comment by bekriebel** [comment]
This is using v0.4.10? Is this using your own Jitsi server, or the default Beta jitsi meet server?

**Comment by feltz916** [comment]
This is using Jitsi webrtc v0.4.10
Connecting to my own server, hosted on Digital Ocean with Ubuntu, using stable jitsi branch.

**Comment by bekriebel** [comment]
If you get the chance, can you try with the default server so we can rule out something unique to your server configuration?

**Comment by TabletopsAndAnvils** [comment]
Can confirm. Also using my own server, hosted on DO with Ubuntu, using their droplet for Jitsi. Some players I can see, some can see me, generally we can hear each other, most I can't see. When pulling up the Jitsi page from my server everything works fine. If I 'Use full Jitsi Client' we've been sometimes seeing double streams (two of user A, two of B but one of C and a stream from the game itself which, even with AV disabled, still seems to be pushing audio back to the client page). Default server seems to break when switching back to it, even after reloading the page the AV windows don't seem to want to appear. Switch back to my custom servers, same thing. However, loading the jitsi page on my server and starting a different room and having a dozen users in it works just fine.

Console is throwing out these errors every half second as well concerning jitsi-remote-control and jitsi-power-monitor:

jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: iframe#{"postis":true,"scope":"jitsi-remote-control","method":"__ready__","params":"1608835334590.7627"}
    at Function.se.error (jquery.min.js:2)
    at se.tokenize (jquery.min.js:2)
    at se.select (jquery.min.js:2)
    at Function.se [as find] (jquery.min.js:2)
    at S.fn.init.find (jquery.min.js:2)
    at new S.fn.init (jquery.min.js:2)
    at S (jquery.min.js:2)
    at inlineviewer.js:117
se.error @ jquery.min.js:2
se.tokenize @ jquery.min.js:2
se.select @ jquery.min.js:2
se @ jquery.min.js:2
find @ jquery.min.js:2
S.fn.init @ jquery.min.js:2
S @ jquery.min.js:2
(anonymous) @ inlineviewer.js:117

jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: iframe#{"postis":true,"scope":"jitsi-power-monitor","method":"__ready__","params":"1608835336213.0334"}
    at Function.se.error (jquery.min.js:2)
    at se.tokenize (jquery.min.js:2)
    at se.select (jquery.min.js:2)
    at Function.se [as find] (jquery.min.js:2)
    at S.fn.init.find (jquery.min.js:2)
    at new S.fn.init (jquery.min.js:2)
    at S (jquery.min.js:2)
    at inlineviewer.js:117
se.error @ jquery.min.js:2
se.tokenize @ jquery.min.js:2
se.select @ jquery.min.js:2
se @ jquery.min.js:2
find @ jquery.min.js:2
S.fn.init @ jquery.min.js:2
S @ jquery.min.js:2
(anonymous) @ inlineviewer.js:117 

![Screen Shot 2020-12-24 at 1 55 26 PM](https://user-images.githubusercontent.com/76455772/103104855-d6540000-45f7-11eb-8c7c-f0cf03f3d575.png)
't see but they can see themselves. It's all messed up. 
![Screen Shot 2020-12-19 at 12 31 27 AM](https://user-images.githubusercontent.com/76455772/103104853-cfc58880-45f7-11eb-9333-66099981f330.png)

**Comment by danberg** [comment]
I was having the same problem. Tried everything I could think of, but could not get it to work. Connecting directly to Jitsi worked. Self hosted on Ubuntu. 

I reinstalled jitsi after the session and have not yet tested if the problem persists. Possibly connected to #50 as I was not using authentication.

When allowing connections directly through jitsi, how do I prevent double video boxes for every user? (One for in-foundry connection, on for jitsi connection)?

Missed previous post as it came when I was writing mine, but also noticed the “If I 'Use full Jitsi Client' we've been sometimes seeing double streams (two of user A, two of B but one of C and a stream from the game itself which, even with AV disabled, still seems to be pushing audio back to the client page)” If I remember correctly.

In the end we fell back to a separate google meet this time.

**Comment by TabletopsAndAnvils** [comment]
Just took it a step further, turned off the Jitsi Module, turned off the AV chat, reset the game server on google cloud, reset the jitsi server on digital ocean, logged back in, turned on AV chat (nothing, not even a video window), re-enabled the Jitsi module. Player can see my video, their window is black but we can both hear each other. So still not working as intended and it may have broke the FVTT native chat, or at least it doesn't want to work now without the Jitsi module loaded. Oh, and switching to the beta server makes my window go black, switching back to my own server makes it re-appear, at least for me.

**Comment by bekriebel** [comment]
I’ll test this out some more over the holiday. If anyone is on the discord and would be comfortable sharing temporary jitsi credentials for their server, I can try that out directly. Feel free to DM me there (bekit#8423)

**Comment by TabletopsAndAnvils** [comment]
> bekit#8423

Sent over some temp credentials, thanks!

**Comment by bekriebel** [comment]
@TabletopsAndAnvils Thanks! I'll test it out soon. Regarding the FVTT native chat, we shouldn't be affecting that at all. I don't touch anything regarding the chat system. I would recommend trying to disable all modules temporarily and see if something else is affecting that.

**Comment by bekriebel** [comment]
Thanks to @TabletopsAndAnvils for giving me a server to test with. I found the issue affecting his server, so hopefully it fixes it for everyone else as well. @feltz916 and @danberg, can you try out the v0.4.11 version that was published today and let me know if that resolves the issue for you as well?

One thing to note, there is still an error being put into the console. I'm trying to see if that's something on my end or Jitsi's. The error doesn't seem to be affecting actual use of the module, though.

**Comment by TabletopsAndAnvils** [comment]
Thanks @bekriebel - Once again, you've given me confidence in my choice of a VTT - Foundry is the only one out there with this type of community, from users to developers, you can not find one better or more involved. Enjoy a Merry Christmas or whatever observance you desire, everyone, and keep on rolling those dice!

**Comment by danberg** [comment]
@bekriebel I just tried 0.4.11 with three participants, and everything worked great!  (I have also reinstalled jitsi and enabled authentication)

Thanks! 🥇

**Comment by bekriebel** [comment]
This appears to be resolved. The `SyntaxError: Unexpected end of JSON input` error seems to be directly related to the droplet installation and does not seem to cause any connectivity problems. I created and closed a ticket (#53) referencing it in case anyone wonders why it is happening.

**Comment by feltz916** [comment]
finally got a chance to test it, working great for me! I only had one user with issues, but im fairly confident it was due to a bad setup (Mac, using Chrome beta browser, and lack of technical knowledge) So 7/8 users were connecting flawlessly.
