### ISSUE TITLE
Issue with audio on Chrome

### ISSUE THREAD

**Issue by SimonR22** [luvolondon/fvtt-module-jitsiwebrtc#56]
First off, thank you for the amazing integration. It works perfectly fine for 4 out of my 5 players.

My last player can't get the audio (video is disabled) to work. 

Using the native jitsi  at jitsi.mydomain.com, his audio works perfectly fine. When connecting to foundry (locally hosted), chrome console throws me this log: 

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/45527224/104597668-e5b5ee80-5675-11eb-8e11-1619f9b089e4.PNG">

While investigating, I noticed that windows 10 microphone activation notification appears for like 1 sec in the task bar when launching foundry on chrome and then disappears again. 

Any leads on how to solve this ?

**Comment by bekriebel** [comment]
@SimonR22
1. Can you expand the `s` object on the second error?
2. Is this a log from your end, or from the player who can't get audio working's end? If not from the player's, is there any way to get that log?
3. It this user the only one with video disabled, or is video disabled for the server?

Thanks!

**Comment by SimonR22** [comment]
Thank you for your prompt answer ! 👍 

1. Feel free to ask if you want me to expand more some parts :)
<img width= 404 src="https://user-images.githubusercontent.com/45527224/104640426-c4bac100-56a8-11eb-9029-d7bacefe5f27.png">

2. From the player's end. How shall I provide you that log ?
3. Video disabled for the server.

**Comment by bekriebel** [comment]
@SimonR22 I think I found the issue. Can you try out v0.4.12 and see if the issue is resolved?

Thanks!

**Comment by SimonR22** [comment]
@bekriebel I tested it aaaand... It works perfectly !!! Issue solved 💯 Awesome work !!!

Out of curiosity, what was causing the issue ?

**Comment by bekriebel** [comment]
Excellent!

There was some logic in place that was supposed to handle when either audio or video wasn't available. However, this was missing some cases for that and it would still try to initiate both audio and video and then fail if either one failed. Also, even if the server was set to only use audio or video or a user was configured for only one, it was still trying to request access to both types of devices.

I improved the logic around retrying when it can't access a device type and also made it smarter with what it is requesting.
