### ISSUE TITLE
Share Screen Functionality?

### ISSUE THREAD

**Issue by mentalic-mutant** [luvolondon/fvtt-module-jitsiwebrtc#57]
Is it possible?

**Comment by bekriebel** [comment]
I actually recently added this for testing purposes. This isn't a supported feature and I have no plans of adding additional functionality or a UI around it. However, you can activate screen share with a macro or from the dev console by running `game.webrtc.client._shareDesktopTracks();` and return to normal camera/video sharing by running `game.webrtc.client._initializeLocal(game.webrtc.client.settings.client);`.

The original functionality was added in this commit: https://github.com/luvolondon/fvtt-module-jitsiwebrtc/commit/db9e615959594f7d5318af60ed666c5743659fba

**Comment by mentalic-mutant** [comment]
I just tried this but it doesnt seem to work.
Error:
message: "Failed to detect desktop picker"
name: "gum.electron_desktop_picker_not_found"

**Comment by bekriebel** [comment]
Is this using the electron app version of Foundry? That will almost
certainly not work. I’ve only tested it from Chrome and Edge.

**Comment by mentalic-mutant** [comment]
Ya, works fine in the browser but it does not work in the app.

**Comment by bekriebel** [comment]
That makes sense. It seems electron doesn’t have the ability to handle a screen share request.
