### ISSUE TITLE
Error: Audio output device change is not supported

### ISSUE THREAD

**Issue by caewok** [luvolondon/fvtt-module-jitsiwebrtc#59]
Foundry 0.7.9, dnd5e 1.2.3, Firefox 84.0.2, Mac OS X 10.15.7, JitsiWebRTC 0.4.14. I am getting many of the following errors, starting when loading a map and continuing throughout the game:

> Uncaught (in promise) Error: Audio output device change is not supported
>     setAudioOutput JitsiTrack.js:478
>     setUserVideo jitsirtc.js:381
>     onRender foundry.js:50361
>     _render foundry.js:21880
>     render foundry.js:4479
>     render foundry.js:21871
>     render foundry.js:50346
>     timeoutId foundry.js:1470
>     setTimeout handler*debounce/< foundry.js:1469
>     _onRemoteTrackAdded jitsirtc.js:756
>     emit events.js:157
>     onRemoteTrackAdded JitsiConference.js:1792
>     emit events.js:152
>     _createRemoteTrack TraceablePeerConnection.js:913
>     _remoteTrackAdded TraceablePeerConnection.js:843
>     ontrack TraceablePeerConnection.js:321
> JitsiTrack.js:478:16
>     setAudioOutput JitsiTrack.js:477
>     setUserVideo jitsirtc.js:381
>     onRender foundry.js:50361
>     _render foundry.js:21880
>     InterpretGeneratorResume self-hosted:1468
>     AsyncFunctionNext self-hosted:674
>     (Async: async)
>     render foundry.js:4479
>     render foundry.js:21871
>     render foundry.js:50346
>     render self-hosted:1161
>     timeoutId foundry.js:1470
>     (Async: setTimeout handler)
>     debounce foundry.js:1469
>     _onRemoteTrackAdded jitsirtc.js:756
>     _onRemoteTrackAdded self-hosted:1161
>     apply self-hosted:2644
>     emit events.js:157
>     onRemoteTrackAdded JitsiConference.js:1792
>     <anonymous> self-hosted:1161
>     apply self-hosted:2644
>     emit events.js:152
>     _createRemoteTrack TraceablePeerConnection.js:913
>     _remoteTrackAdded TraceablePeerConnection.js:843
>     ontrack TraceablePeerConnection.js:321
>     dispatchEvent PeerConnection.jsm:798
>     dispatchEvent PeerConnection.jsm:1831
>     fireTrackEvent PeerConnection.jsm:1985

Using the Public Jitsi Meeting Beta and all default settings for the Jitsi module.

**Comment by bekriebel** [comment]
Does the module still function properly, or is it causing some type of issue as well? This may be an os/browser specific issue that I just have to catch and ignore if it isn’t causing any actual issues.

**Comment by caewok** [comment]
Hard to say whether the module is functioning properly. Last few sessions, I got a lot of freezing images, and several people had to log out and back in again after their connections stopped working. So I have been trying to troubleshoot various errors to see if I can get a more stable setup. This "Audio output device change is not supported" error is particularly troubling, in that it tends to repeat over and over in the console as the session progresses. Seems to happen even if no audio is playing on the scene and nothing has changed in the a/v setup (no changing headphones, mic input, etc.).

**Comment by bekriebel** [comment]
Ahh... I see the issue. FireFox does not allow for setting the audio output device on an HTML 5 <video> tag. This is why the option isn't shown in Foundry for setting that device either. I'm pushing a fix in a moment to account for this.

However, I don't think this is related to the freezing and other disconnects. This is being tracked in #54. Any addition information you can provide would be helpful.

In particular, I'm not sure why this error kept being shown in your logs. This code should only have been run when a new video or audio track was added to or removed from the meeting, which should only happen when a user joins or leaves. If there are other cases where that is happening, please add other information you have to the other issue.

Thanks!
