### ISSUE TITLE
Warning: The description does not look like plan-b

### ISSUE THREAD

**Issue by caewok** [luvolondon/fvtt-module-jitsiwebrtc#60]
Foundry 0.7.9, dnd5e 1.2.3, Firefox 84.0.2, Mac OS X 10.15.7, JitsiWebRTC 0.4.14. Getting one or two of these mysterious warnings, which Google suggests is related to Jitsi:

> The description does not look like plan-b interop.js:328:20

See 
https://community.jitsi.org/t/lib-jitsi-meet-dependency-missing-result-the-description-does-not-look-like-plan-b/76261
https://github.com/jitsi/lib-jitsi-meet/issues/1382

Could be related to #59.

**Comment by bekriebel** [comment]
Can you go to https://beta.meet.jit.si and start a meeting and see if you get the same errors in the console? A lot of random errors like this are coming from the jitsi library itself and there’s not really anything that I can do about them until they are dealt with upstream.

**Comment by caewok** [comment]
Yes, the plan-b warning shows up there too. I will close this.

**Comment by zsinba** [comment]
how to resolve it now?

**Comment by bekriebel** [comment]
@zsinba This doesn't seem to be an actual error that affects the module. If it were to be fixed, it would need to be fixed on the Jitsi code side since it's not something the module directly controls.

**Comment by zsinba** [comment]
This is persistent, but doesn't seem to affect usage, just a constant reminder
