### ISSUE TITLE
X-talk between worlds?

### ISSUE THREAD

**Issue by 736dave** [luvolondon/fvtt-module-jitsiwebrtc#66]
When I join one world, my feed appears as normal in that world but ALSO appears in the other world hosted from the same Forge server.  This seems to happen even if I connect as a different user from a different network.

Both worlds are all hosted on the same (Forge) service with multiple Foundry licenses.
Foundry settings have been copied between worlds so maybe all accidentally all joining the same 'room'?

Thanks for the awesome module.

![Screen Shot 2021-03-10 at 12 48 22 PM](https://user-images.githubusercontent.com/38968641/110698524-9cc87500-81a2-11eb-98cf-a7f27a3f2605.png)

**Comment by bekriebel** [comment]
If settings were copied between them, that explains it. The room that it joins is saved as a foundry setting. You can reset the room on one of them by running the following in the developer console: 
```js
game.webrtc.client.settings.set("world", "server.room", randomID(32));
```

**Comment by 736dave** [comment]
That worked for me, Thanks.  Yet another thing I have to be careful to clear from my export files before I import or share them :-)

**Comment by bekriebel** [comment]
Great! I've been meaning to add a settings button that lets you reset the room name. I just opened #67 to remind myself to do that soon :-)
