### ISSUE TITLE
Low Frame Rate with 0.5.3

### ISSUE THREAD

**Issue by Dick-K** [luvolondon/fvtt-module-jitsiwebrtc#71]
Please ignore, more analysis at my end required.

ETA: Yes, it appears to be an issue with the integral webcam in the old laptop I use for testing. Apologies.

**Comment by bekriebel** [comment]
Actually, something does seem to be going on. I can repro this as well, but not just with 0.5.3. I think it may actually be a change that has happened on the beta.meet.jit.si servers. If I switch to using meet.jit.si, framerate improves.

**Comment by Dick-K** [comment]
Okay, I'll give that a shot. Thanks for getting back to me anyway, and so
quickly. Many thanks, your module is a life-saver 👍cheers

**Comment by bekriebel** [comment]
I've found the issue as well. It looks like they've enabled an experimental feature on the beta servers that is causing the lag. I can override the setting to fix it. I'll push an update later today with this change. Thanks for reporting it!

**Comment by Dick-K** [comment]
Yes, I concur. I previously specified the signalling server as the
embedded *Public
Jitsi Meet Beta* and the relay server as *meet-jit-si-turnrelay.jitsi.net
<http://meet-jit-si-turnrelay.jitsi.net>*.

Using *meet.jit.si <http://meet.jit.si>* on its own with the relay server
set to *meet-jit-si-turnrelay.jitsi.net
<http://meet-jit-si-turnrelay.jitsi.net>* made no difference but using
*meet.jit.si
<http://meet.jit.si> with* the relay server set to *Provided by signalling
server* appears to have restored an acceptable framerate.

Thanks again.

**Comment by Dick-K** [comment]
Nice job with such a quick and informed response.

**Comment by bekriebel** [comment]
This should be resolved with v0.5.4.

**Comment by Dick-K** [comment]
Just upgraded, it's working fine now. Many thanks Brint, all the best 👍
