### ISSUE TITLE
Link to install tutorial is down

### ISSUE THREAD

**Issue by FumbleBe** [luvolondon/fvtt-module-jitsiwebrtc#72]
Following URL https://www.vttassets.com/articles/installing-a-self-hosted-jitsi-server-to-use-with-foundry-vtt (referred in readme) is down.

**Comment by bekriebel** [comment]
Thanks. I'll have to find or make a new tutorial. In the meantime, I actually suggest just using the default public Jitsi server.

**Comment by amayausky** [comment]
To save you some time, it looks like the tutorial was just moved to a new domain rather than removed: https://vtta.io/articles/installing-a-self-hosted-jitsi-server

**Comment by FumbleBe** [comment]
Thanks for caring, I do not need it in fact :) It was just, you know, to don't leave a dead link in the documentation !

But thank you !

We probably can close this issue ;)

**Comment by bekriebel** [comment]
Thanks, @amayausky! I pushed a change with the new link.
