### ISSUE TITLE
Change standard settings from "PPT" to "Always Enabled"

### ISSUE THREAD

**Issue by Gorvaine** [luvolondon/fvtt-module-jitsiwebrtc#74]
Every time a new player enters my games I have to explain them how to change this setting, clicking the cog, changing the dropdown menu, saving...

Is it possible to have this option setted by default at "Always Enabled" or at least, a checkbox on the config would be nice.

**Comment by bekriebel** [comment]
This is a default set by the core FoundryVTT app. Though it could be overridden, I try not to modify core settings with this module. I'm going to add this as a feature request for my WebRTC Tweaks module - I think it fits better into the use case for that one.
