### ISSUE TITLE
Allow jitsi to be enabled/disabled on a per user basis?

### ISSUE THREAD

**Issue by Seamonster73** [luvolondon/fvtt-module-jitsiwebrtc#79]
This is either a question or a (probably very niche) dev request:

I have two players (out of a group of five) that are accessing Foundry on old/low-spec laptops. In order to free up some CPU & Network bandwidth, I tried setting them up with the Jitsi mobile app and asked them to use that to join the videochat via the standalone Jitsi link. This worked, and allowed them to switch the webcams on their laptops off thereby freeing up bandwidth. 

However there seems no way for them to disable the incoming video from other players in the Foundry browser window. Therefore they receive the incoming video from other players twice* via their network - once to the Foundry window and once to the videochat call they have running on their mobile device. Conversely the other members of the group (who have high-spec PCs and prefer to have Jitsi running in the browser via Foundry) see the video from the first group's mobile device and blank videochat windows from their now disabled webcams.

Therefore, is there (or could there be) a way for each user to independently control whether they have Jitsi running in Foundry? Currently it seems that the GM can only enable/disable audio/video chat for all players or none. Alternatively, is there a way the GM could be allowed to enable/disable on a per user basis to improve performance for those with low spec machines, and reduce screen clutter?

*Actually they receive the video stream three times, as the two players live together and play on separate laptops. As such their network connection can get a bit swamped...

**Comment by bekriebel** [comment]
This is something that users can already do. Under the module settings on the user’s side, they can check the option for Use Full Jitsi Meet Client. This will prompt them with a button to join the meeting when they sign in, but they can just dismiss that if they are already signing in with their phones. With that option selected, the entire video conferencing system will be turned off on their end. I think this gives what you are looking for.

**Comment by Seamonster73** [comment]
Fantastic. I had no idea that existed.

Thank you very much for the quick response.
