### ISSUE TITLE
[Bug] joining player video does not appear until I change the video size

### ISSUE THREAD

**Issue by jeromebruzaud** [luvolondon/fvtt-module-jitsiwebrtc#8]
When a person joins, his/her video appears with the default image on his/her screen. The default image stays until he/she clicks on the video size button. Once the video size button is clicked, everything works perfectly.

Note that the video appears normally on other people screens. It is a "local" issue.

This is using your plugin with basic "Foudry VTT" server.

This is a minor bug :)

**Comment by luvolondon** [comment]
Hi,
thank you for your feedback. This should be fixed now. When registering the local stream to the conference it did not wait for the promise to be returned. Please try the new release.

**Comment by jeromebruzaud** [comment]
This is fixed. Thanks !
