### ISSUE TITLE
Failed to locate server for audio/video.

### ISSUE THREAD

**Issue by heliobolseiro** [luvolondon/fvtt-module-jitsiwebrtc#83]
hi, i'm trying to hook up a video/audio in my foundry vtt. I created a certificate and placed the certificate and key in foundry vtt, however, it does not find the certificate, leaving this message only. Player videos / audios do not appear. What could be happening?

![image](https://user-images.githubusercontent.com/84214182/127405801-152ed000-a49c-45c0-adeb-48bc8e723f7e.png)

**Comment by bekriebel** [comment]
I'm not quite sure what you are referring to. The Jitsi module itself doesn't use certificates. You do need to be using SSL on the Foundry Server (a browser requirement for using WebRTC). If your Foundry server isn't picking up the certificate properly, you may want to ask for some help on the Foundry community Discord server, as I'm not sure what the issue with that would be.

The screenshot you provided looks accurate. Picking "Foundry VTT" there will just the default `beta.meet.jit.si` server.

**Comment by bekriebel** [comment]
Closing with no response. If this is still an issue, please provide more details.
