### ISSUE TITLE
Ability to use virtual backgrounds when using custom server

### ISSUE THREAD

**Issue by Cromagnonaut** [luvolondon/fvtt-module-jitsiwebrtc#87]
First of all, thank you for maintaining this project. Its a small life-saver for my desktop real-estate :)

If a [https://beta.meet.jit.si/](url) session is hosted, all settings are available through the standard interface. But not with a self-hosted instance and custom url. 
Would it be possible to implement an option for the virtual backgrounds feature when using a self-hosted instance in the future? This would be nice to surprise my players now an then ;)

**Comment by bekriebel** [comment]
Are you asking for the virtual background controls to be available through the module, or through the Jitsi Web interface? I know that the module originally had some support for this, but the resource usage was quite high when combined with FVTT and it was a bit of a pain to maintain, so it was removed.

If this is something you are looking for in the Jitsi Web interface, then this is something that would need to be done by the Jitsi team and I'd recommend opening an issue on their community forum: https://community.jitsi.org/
