### ISSUE TITLE
Player using Firefox has pixelated image

### ISSUE THREAD

**Issue by simulacrum-1** [luvolondon/fvtt-module-jitsiwebrtc#88]
One of my players has been using Chrome. But recently switched to Firefox. His image in fine in Chrome but is pixelated in Firefox.

**Comment by bekriebel** [comment]
Unfortunately, this seems to be an issue with Jitsi and Firefox. I found that the same issues occurred when using the standard Jitsi interface, so there isn't really much I can do on the module side to fix this.

**Comment by simulacrum-1** [comment]
Thanks for checking.
