### ISSUE TITLE
connection refused from different world

### ISSUE THREAD

**Issue by hede0n** [luvolondon/fvtt-module-jitsiwebrtc#9]
have setup jitsi module on one world, and everything works beautifully. However, using exactly the same configuration (checked multiple times) on another world will get connections refused by jitsi server. ` has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by bekriebel** [comment]
@hede0n Make sure you have enabled the Jitsi module for the second world. I had forgotten to do this at one point and I think I saw the same CORS error. It throws that because the default WebRTC implementation tries to hit a path on the server that Jitsi doesn't undestand.

**Comment by hede0n** [comment]
This was exactly it. Jesus, I feel stupid. I had no idea that I have to enable this module on a "per world" basis. Thanks. That is it

**Comment by bekriebel** [comment]
Hehe, don't feel bad. I've lost count of how many times I've done that. Really need a "world settings sync" module, too 😂 

@luvolondon, looks like this could be closed.
