### ISSUE TITLE
Version 0.6.3 prevents opening of A/V Configuration

### ISSUE THREAD

**Issue by DarioRomano** [luvolondon/fvtt-module-jitsiwebrtc#90]
Hello!

I'm fairly certain that since the update there seems to be an issue with this module, where when I activate it, I'm not able to open the "Configure Audio/Video" dialog from the general options anymore. If I can generate any logs I can upload to reproduce or analyze this error, please let me know. 

I'm using module version 0.6.3 and FoundryVTT version 0.8.9

**Comment by bekriebel** [comment]
Thanks for reporting this! It's been fixed in [v0.6.4](https://github.com/luvolondon/fvtt-module-jitsiwebrtc/releases/tag/v0.6.4).

https://github.com/luvolondon/fvtt-module-jitsiwebrtc/commit/c055ae5d87ac5de0fea15292f08cc0e170fc6564
